#!/usr/bin/env bash
set -Eeo pipefail
shopt -s globstar
. commands.sh

function version() {
  export BRANCH=${CIRCLE_BRANCH-$(git rev-parse --abbrev-ref HEAD)}
  export BUILD_NUMBER=${CIRCLE_BUILD_NUM-$(date -u +"%Y%m%d%H%M%S")}
  export REVISIONS=$(git rev-list --count ${BRANCH})
  export VERSION=0.${REVISIONS}.${BUILD_NUMBER}

  echo version: ${VERSION}
}

function clean() {
  rm -rf artifacts
  bun install > /dev/null 2>&1
}

function check() {
  bun run --bun tsc --noEmit
}

function test() {
  bun test "$@"
}

function coverage() {
  test --coverage
}

function dev() {
  test --watch
}

function build-client() {
  local option=${1}
  local src="./src"
  local dest="./www"

  if [[ "${option}" == "--watch" ]]; then
    bun build --watch --minify "${src}/client/main.ts" "${src}/cards/main.ts" --outdir "${dest}/" &
    watchexec -w "${src}" --exts css bunx lightningcss --minify --bundle "${src}/client/main.css" --output-dir "${dest}/client/" &
  else
    bun build --minify "${src}/client/main.ts" "${src}/cards/main.ts" --outdir "${dest}/"
    bunx lightningcss --minify --bundle "${src}/client/main.css" --output-dir "${dest}/client/"
  fi
}

function build() {
  check
  build-client "$@"
  test "$@"
}

function start() {
  check
  build-client --watch
  bun run --watch src/bun/app.ts
}

function startw() {
  check
  build-client
  sed -n '/# CUT HERE/q;p' wrangler.toml > wrangler-local.toml
  wrangler -c wrangler-local.toml dev --remote --port 3000
}

function tail() {
  wrangler tail
}

function check-rclone() {
    : "${RCLONE_CONFIG_CLOUDFLARE_ACCESS_KEY_ID?Required}"
    : "${RCLONE_CONFIG_CLOUDFLARE_SECRET_ACCESS_KEY?Required}"
    : "${RCLONE_CONFIG_CLOUDFLARE_ENDPOINT?Required}"
}

function deploy() {
  check
  echo ${HONEYCOMB_API_KEY?Required} | wrangler secret put HONEYCOMB_API_KEY
  wrangler deploy
  check-rclone
  rclone --config rclone.conf copy www/ cloudflare:talebrary --header="Cache-Control:public, max-age=60" -v
}

function pull() {
  check-rclone
  rclone --config rclone.conf copy cloudflare:talebrary/content www/content/ --metadata -v
}

function ci() {
  check
  build-client
  coverage
  deploy
}

clean

command="${1-build}"
set +e; shift; set -Eeo pipefail;
$command "$@"
