#!/usr/bin/env bash
set -Eeo pipefail
shopt -s globstar
. commands.sh

function version() {
  export BRANCH=${CIRCLE_BRANCH-$(git rev-parse --abbrev-ref HEAD)}
  export BUILD_NUMBER=${CIRCLE_BUILD_NUM-$(date -u +"%Y%m%d%H%M%S")}
  export REVISIONS=$(git rev-list --count ${BRANCH})
  export VERSION=0.${REVISIONS}.${BUILD_NUMBER}

  echo version: ${VERSION}
}

function tag() {
  version

  git config --global user.name "Server"
  git config --global user.email "server@bodar.com"
  git tag -a ${VERSION} -m "Release ${VERSION}"
  git push origin ${VERSION}
}

function clean() {
  rm -rf artifacts
}

function check() {
  bun install
  #deno check {src,test}/**/*.ts
  #deno lint --compact
}

function test() {
    bun test "$@"
}

function test-with-coverage() {
    mkdir -p artifacts/coverage
    #test --junit-path=artifacts/test-results --coverage=artifacts/coverage
    #deno coverage --lcov artifacts/coverage/ --output=artifacts/coverage.lcov
}

function dev() {
  test --watch
}

function build() {
  check
  test
}

function start() {
  check
  wrangler dev --remote
}

function deploy() {
  check
  wrangler deploy
  rclone --config rclone.conf sync www/ cloudflare:talebrary --header="Cache-Control:public, max-age=60"
}

function ci() {
  check
  test
 # test-with-coverage
  #tag
  deploy
}

clean

command="${1-build}"
set +e; shift; set -Eeo pipefail;
$command "$@"
