/* eslint-disable */
// Generated by Wrangler by running `wrangler types --no-include-runtime` (hash: 854704726d2361068396a0507293f9be)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/cloudflare/app");
	}
	interface Env {
		r2: R2Bucket;
		db: D1Database;
		ai: Ai;
		RCLONE_CONFIG_CLOUDFLARE_ACCESS_KEY_ID: string;
		RCLONE_CONFIG_CLOUDFLARE_SECRET_ACCESS_KEY: string;
		RCLONE_CONFIG_CLOUDFLARE_ENDPOINT: string;
		WORKFLOW: Workflow /* CloudflareWorkflow from src/cloudflare/CloudflareWorkflow.ts */;
		IFARCHIVE_PROXY: DurableObjectNamespace /* IfArchiveProxy from src/cloudflare/IfArchiveProxy.ts */;
	}
}
interface Env extends Cloudflare.Env {}
