/* eslint-disable */
// Generated by Wrangler by running `wrangler types --no-include-runtime` (hash: 9ae3615784027564a1c9cb1a75266ade)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/cloudflare/app");
		durableNamespaces: "IfArchiveProxy";
	}
	interface Env {
		r2: R2Bucket;
		db: D1Database;
		ai: Ai;
		CLOUDFLARE_ACCOUNT_ID: string;
		CLOUDFLARE_API_TOKEN: string;
		RCLONE_CONFIG_CLOUDFLARE_ACCESS_KEY_ID: string;
		RCLONE_CONFIG_CLOUDFLARE_SECRET_ACCESS_KEY: string;
		RCLONE_CONFIG_CLOUDFLARE_ENDPOINT: string;
		PROXY_URL: string;
		PROXY_TOKEN: string;
		IFARCHIVE_PROXY: DurableObjectNamespace<import("./src/cloudflare/app").IfArchiveProxy>;
		COVER_ART_WORKFLOW: Workflow<Parameters<import("./src/cloudflare/app").CoverArtWorkflow['run']>[0]['payload']>;
		ILLUSTRATION_WORKFLOW: Workflow<Parameters<import("./src/cloudflare/app").IllustrationWorkflow['run']>[0]['payload']>;
	}
}
interface Env extends Cloudflare.Env {}
