/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 153cbf2daa6bd935a4b0863b8067cdcf)
interface __BaseEnv_Env {
	r2: R2Bucket;
	db: D1Database;
	ai: Ai;
	TRANSCRIPTS: import("cloudflare:pipelines").Pipeline<Cloudflare.TalebraryTranscriptsRecord>;
	BETTER_AUTH_SECRET: string;
	BETTER_AUTH_URL: string;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	BETTER_AUTH_API_KEY: string;
	RCLONE_CONFIG_CLOUDFLARE_ACCESS_KEY_ID: string;
	RCLONE_CONFIG_CLOUDFLARE_SECRET_ACCESS_KEY: string;
	RCLONE_CONFIG_CLOUDFLARE_ENDPOINT: string;
	PROXY_URL: string;
	PROXY_TOKEN: string;
	IFARCHIVE_PROXY: DurableObjectNamespace<import("./src/cloudflare/app").IfArchiveProxy>;
	COVER_ART_WORKFLOW: Workflow<Parameters<import("./src/cloudflare/app").CoverArtWorkflow['run']>[0]['payload']>;
	ILLUSTRATION_WORKFLOW: Workflow<Parameters<import("./src/cloudflare/app").IllustrationWorkflow['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/cloudflare/app");
		durableNamespaces: "IfArchiveProxy";
	}
	type TalebraryTranscriptsRecord = { session_id: string; game_id: string; seq: number; input_type: string; input_text?: string; output_text?: string; input_at?: string | number; output_at?: string | number; received_at: string | number; input?: Record<string, unknown>; output?: Record<string, unknown> };
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
