compatibility_date = "2024-05-08"
name = "talebrary"
main = "src/app.ts"

[[d1_databases]]
binding = "db"
database_name = "talebrary"
database_id = "72a0543e-663c-4bf0-bc0e-c24bcd666888"

[[r2_buckets]]
binding = 'r2'
bucket_name = 'talebrary'
preview_bucket_name = 'talebrary'