compatibility_date = "2025-02-03"
name = "talebrary"
main = "src/cloudflare/app.ts"

[observability]
enabled = true
head_sampling_rate = 1

[[d1_databases]]
binding = "db"
database_name = "talebrary"
database_id = "72a0543e-663c-4bf0-bc0e-c24bcd666888"

[[r2_buckets]]
binding = 'r2'
bucket_name = 'talebrary'
preview_bucket_name = 'talebrary'

[ai]
binding = "ai"

[[durable_objects.bindings]]
name = "IFARCHIVE_PROXY"
class_name = "IfArchiveProxy"

[[migrations]]
tag = "v1"
new_classes = ["IfArchiveProxy"]

[[workflows]]
name = "talebrary"
binding = "WORKFLOW"
class_name = "CloudflareWorkflow"
script_name = "src/cloudflare/CloudflareWorkflow.ts"
