export const AdjustKeys: Record<string, string> = {
    'ArrowLeft': 'left',
    'ArrowRight': 'right',
    'ArrowUp': 'up',
    'ArrowDown': 'down',
    'Enter': 'return',
    'F1': 'func1',
    'F2': 'func2',
    'F3': 'func3',
    'F4': 'func4',
    'F5': 'func5',
    'F6': 'func6',
    'F7': 'func7',
    'F8': 'func8',
    'F9': 'func9',
    'F10': 'func10',
    'F11': 'func11',
    'F12': 'func12',
};
