// Generate a safe, atomic D1 upload from the local build (db/talebrary.sqlite).
//
// Strategy (see db/run upload()):
//   - talebrary_games:     UPSERT — never blanket-delete, so incoming FKs
//                          (e.g. a future favourites.game_id) stay valid, and
//                          curation columns (enabled, notes) are preserved by
//                          omitting them from the ON CONFLICT update.
//   - talebrary_gamelinks: full DELETE + INSERT — IFDB owns this table and
//                          nothing user-defined references it.
//   - talebrary_search:    full DELETE + INSERT — derived FTS index.
//   - auth tables:         NEVER emitted — structurally impossible to clobber.
//
// The whole file executes as ONE implicit transaction on D1 (verified atomic at
// 50k statements), so readers see all-old or all-new — no empty-table window.
// D1 forbids explicit BEGIN/COMMIT, so none are emitted.
import {Database} from "bun:sqlite";

const db = new Database(process.env.DB_PATH ?? "db/talebrary.sqlite", {readonly: true});

const GAME_COLS = ["id","title","author","description","genre","language","published",
    "coverart","tags","seriesname","avg_rating","enabled","notes","ifdb_moddate","synced_at"];
// Curation columns are owned by prod, not IFDB — never overwrite them on update.
const GAME_PRESERVE = new Set(["id","enabled","notes"]);
const LINK_COLS = ["game_id","url","format","extension","display_order"];
const SEARCH_COLS = ["id","title","author","tags","description","seriesname","genre"];

function lit(v: unknown): string {
    if (v === null || v === undefined) return "NULL";
    if (typeof v === "number") return Number.isFinite(v) ? String(v) : "NULL";
    if (typeof v === "bigint") return v.toString();
    return "'" + String(v).replace(/'/g, "''") + "'";
}

const out = Bun.stdout.writer();
const w = (s: string) => out.write(s);

w("-- Generated by db/gen-upload.ts — safe atomic refresh of catalogue tables.\n");
w("-- Auth tables intentionally excluded. No BEGIN/COMMIT (D1 wraps the file).\n\n");

// 1. games: upsert (preserve enabled/notes)
const setClause = GAME_COLS.filter(c => !GAME_PRESERVE.has(c))
    .map(c => `${c}=excluded.${c}`).join(", ");
for (const row of db.query(`SELECT ${GAME_COLS.join(",")} FROM talebrary_games`).all() as any[]) {
    const vals = GAME_COLS.map(c => lit(row[c])).join(",");
    w(`INSERT INTO talebrary_games (${GAME_COLS.join(",")}) VALUES (${vals}) `);
    w(`ON CONFLICT(id) DO UPDATE SET ${setClause};\n`);
}

// 2. gamelinks: full replace (IFDB-owned; no incoming FK)
w("\nDELETE FROM talebrary_gamelinks;\n");
for (const row of db.query(`SELECT ${LINK_COLS.join(",")} FROM talebrary_gamelinks`).all() as any[]) {
    const vals = LINK_COLS.map(c => lit(row[c])).join(",");
    w(`INSERT INTO talebrary_gamelinks (${LINK_COLS.join(",")}) VALUES (${vals});\n`);
}

// 3. search: rebuild (derived FTS index)
w("\nDELETE FROM talebrary_search;\n");
for (const row of db.query(`SELECT ${SEARCH_COLS.join(",")} FROM talebrary_search`).all() as any[]) {
    const vals = SEARCH_COLS.map(c => lit(row[c])).join(",");
    w(`INSERT INTO talebrary_search (${SEARCH_COLS.join(",")}) VALUES (${vals});\n`);
}

await out.end();
db.close();
